In [2]:
#built in functions
result = print("test")
print(result , type(result))

test
None <class 'NoneType'>


In [14]:
# function
def AddValue1_Fun(val1):
    """ comments : add 1 with parameter """
    val1 = val1 + 1
    return val1

ret = AddValue1_Fun(10)
print(ret)
    

11


In [12]:
ages = [11, 36, 37, 67]
tickets = [AddValue1(age) for age in ages] 
          
print(tickets)

[12, 37, 38, 68]


In [26]:
#ORDER => keyword followed by positional arguments
def fun_arg(name , age , course ="NUS"):
    print(name,age,course)
    return (name,age,course)

ret = fun_arg("siva","38","Python")
print(ret ,type(ret))
print(fun_arg("siva","38"))

siva 38 Python
('siva', '38', 'Python') <class 'tuple'>
siva 38 NUS
('siva', '38', 'NUS')


In [2]:
#Modules
import statistics
import statistics as st # alias
from statistics import mean as ml #alias for single fun

a_list = [12, -12, 4, 6, 12, 24,-10]

print(st.mean(a_list))
print(st.stdev(a_list))

5.142857142857143
12.746614863413363


In [33]:
#NumPy => core lib for scientific

import numpy as np

array_1d = np.array([2, 3.60, 2.05, 13.50, 18.90])  # Construct an array from a list

print(type(array_1d))                               # Data type of array_1d
print(array_1d.ndim)                                # Number of dimensions
print(array_1d.shape)                               # Shape of the array
print(array_1d.dtype)                               # Type of the data item

print("############")

#2D

nested_list = [[1, 2],    
               [2, 3.5],     
               [5, 6.5]]            # Each inner list specifies a row

array_2d = np.array(nested_list)    # Construct a 2-dimensional array from a nested list  

print( array_2d)


<class 'numpy.ndarray'>
1
(5,)
float64
############
[[ 1.   2. ]
 [ 2.   3.5]
 [ 5.   6.5]]


In [36]:
import numpy as np
USD = [1,100,1000] 
usd_array = np.array(USD) 
print(usd_array)
print(usd_array*1.37)

[   1  100 1000]
[    1.37   137.    1370.  ]


In [8]:
import numpy as np
USD = [1,100,1000] 
SGD = np.array(USD) * 1.37
print(SGD)
usd_array2 = np.array([[1,100,1000] ,[1,101,1001] ]) 
print(usd_array2* 3)


[   1.37  137.   1370.  ]
[[   3  300 3000]
 [   3  303 3003]]


In [19]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

#print(type(np_height))

# Calculate bmi
bmi = np_weight / np_height ** 2

# Print the result
#print(bmi)

# For a boolean response
bmi > 25

# Print only those observations above 25
bmi1 = bmi[bmi > 25]

print(bmi1)


[27.88755755 28.75558507 25.48723993 25.84368152]


In [1]:
#2D array
import numpy as np


arr2D = np.array([[1, 2, 3], [4, 5, 6]])

#print(arr2D , arr.ndim)

print(arr2D[0][0])




1


In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

print(5%3)

[2 4]
2


In [40]:
def func(x, y):

    """This is a function"""

    if x%3 == 0:

        return x

    elif x%3 == 1:

        return y

x = 1

y = 2

print(func(y=x, x=y))

None


In [41]:
def sum_sq(x):

    """This is a function"""

    output = sum([item**2 for item in x])

"""Outside the function"""

x = [1, 1, 1]

y = [2, 2, 2]

print(sum_sq(y))

None


In [42]:
def sum_sq(x):

    output = sum([item**2 for item in x])

    return x

x = [1, 1, 1]

y = [2, 2, 2]

print(sum_sq(y))


[2, 2, 2]


In [43]:
x, y, z = 1, 2, 3

def sum_two(x, y, z):

    """This is a function"""

    return x+y, y+z, x+z

result = sum_two(x, y, z)

a, b = result[::2]

print(str(a) + str(b))

34


In [31]:
def func(x, y):

    """This is a function"""

    if x%3 == 0:

        return x

    elif x%3 == 1:

        return y

x = 1

y = 2

print(func(x, y))

2
